import backend.app.models.entities
"""Add AttendanceAnomaly model

Revision ID: 39ffa3306d5f
Revises: f59139c4500e
Create Date: 2026-09-08 12:08:11.300818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ffa3306d5f'
down_revision: Union[str, None] = 'f59139c4500e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_anomalies',
    sa.Column('id', backend.app.models.entities.GUID(length=36), nullable=False),
    sa.Column('session_id', backend.app.models.entities.GUID(length=36), nullable=True),
    sa.Column('student_id', backend.app.models.entities.GUID(length=36), nullable=True),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', backend.app.models.entities.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_anomalies_anomaly_type'), 'attendance_anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_attendance_anomalies_session_id'), 'attendance_anomalies', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_anomalies_student_id'), 'attendance_anomalies', ['student_id'], unique=False)
    op.create_foreign_key(None, 'attendance_sessions', 'timetable_entries', ['timetable_entry_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subjects', 'theory_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'tutorial_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'practical_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'theory_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'tutorial_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'practical_credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_subjects_vertical'), 'subjects', ['vertical'], unique=False)
    op.create_foreign_key(None, 'timetable_entries', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable_entries', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_vertical'), table_name='subjects')
    op.alter_column('subjects', 'practical_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'tutorial_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'theory_credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'practical_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'tutorial_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subjects', 'theory_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_anomalies_student_id'), table_name='attendance_anomalies')
    op.drop_index(op.f('ix_attendance_anomalies_session_id'), table_name='attendance_anomalies')
    op.drop_index(op.f('ix_attendance_anomalies_anomaly_type'), table_name='attendance_anomalies')
    op.drop_table('attendance_anomalies')
    # ### end Alembic commands ###

